% bemobil_dipfit() - Prepares data for dipole fitting and runs the dipole fitting procedure
%
% Usage:
%   >>  [ EEG ] = bemobil_dipfit( EEG, headmodel,...
% channels_to_include, components_to_fit, RV_threshold,...
% remove_outside_head, fit_bilateral_dipoles)
%
% Inputs:
%   EEG                   - eeglab EEG struct
%   headmodel             - 'evy', 'klaus' or 'BEM'. Uses BEM by default
%   channels_to_include   - Channel indices to include for dipfit montage
%   components_to_fit     - number of specific component to fit, default all = []
%   RV_threshold          - number percentage of residual variance accepted, default is '15'
%   remove_outside_head   - '1' to remove dipoles located outside the head (default)
%   fit_bilateral_dipoles - 'on' or 'off' to dipoles better explained by a bilateral dipole   
%    
% Outputs:
%   EEG     - EEGLAB EEG structure with fitted dipole in EEG.dipfit
%
% See also: 
%   POP_BEMOBIL_DIPFIT, EEGLAB

function [ EEG ] = bemobil_dipfit( EEG, headmodel,...
    channels_to_include, components_to_fit, RV_threshold,...
    remove_outside_head, fit_bilateral_dipoles)

if nargin < 1
	help bemobil_dipfit;
	return;
end;

% check if preprocessed file already exist and break if it does
out_filename = ['Dipfit_' EEG.filename];
dir_files = dir(EEG.filepath);
if ismember(out_filename, {dir_files.name})
    disp(['Warning: dipfit file already exists in: ' EEG.filepath '. ' 'Exiting...']);
    return;
end

if strcmp(headmodel, 'evy') % add later when available
elseif strcmp(headmodel, 'klaus') % add later when available
end

% else use standard BEM headmodel
% change relevant EEG electrode labels so that it matches 10/20
% template
EEG = pop_chanedit(EEG,...
    'changefield',{47 'labels' 'AFz'},...
    'changefield',{48 'labels' 'Fz'},...
    'changefield',{51 'labels' 'FCz'},...
    'changefield',{60 'labels' 'CPz'},...
    'changefield',{110 'labels' 'POz'},...
    'changefield',{124 'labels' 'Iz'},...
    'changefield',{42 'labels' 'F3'},...
    'changefield',{54 'labels' 'F4'},...
    'changefield',{72 'labels' 'P3'},...
    'changefield',{89 'labels' 'P4'},...
    'changefield',{99 'labels' 'P09'},...
    'changefield',{126 'labels' 'PO10'},...
    'changefield',{97 'labels' 'TP9'},...
    'changefield',{128 'labels' 'TP10'},...
    'changefield',{35 'labels' 'C3'},...
    'changefield',{33 'labels' 'C5'},...
    'changefield',{62 'labels' 'C4'},...
    'changefield',{64 'labels' 'C6'});

[newlocs transform] = coregister(EEG.chanlocs,...
    '/Users/lukasgehrke/Documents/MATLAB/eeglab/plugins/dipfit2.3/standard_BEM/elec/standard_1005.elc',...
    'warp', 'auto', 'manual', 'off');

EEG = pop_dipfit_settings( EEG,...
    'hdmfile','/Users/lukasgehrke/Documents/MATLAB/eeglab/plugins/dipfit2.3/standard_BEM/standard_vol.mat',...
    'coordformat','MNI',...
    'mrifile','/Users/lukasgehrke/Documents/MATLAB/eeglab/plugins/dipfit2.3/standard_BEM/standard_mri.mat',...
    'chanfile','/Users/lukasgehrke/Documents/MATLAB/eeglab/plugins/dipfit2.3/standard_BEM/elec/standard_1005.elc',...
    'coord_transform', transform ,...
    'chansel', channels_to_include);

EEG = pop_multifit(EEG, components_to_fit, 'threshold', RV_threshold,...
    'rmout', remove_outside_head, 'dipoles', fit_bilateral_dipoles);

%save data
pop_saveset(EEG, strcat(EEG.filepath, out_filename));
end